spring:
  main:
    banner-mode: off

sentry:
  dsn:
  traces-sample-rate: 1.0
  environment: local
  send-default-pii: on
  enable-user-interaction-tracing: on
  enable-user-interaction-breadcrumbs: on
  ignored-exceptions-for-type:
#    - org.springframework.security.access.AccessDeniedException

spring.datasource:
  driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  url: jdbc:p6spy:postgresql://localhost:5432/db

holiday:
  api: http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService